### PR TITLE
Move sqoop scripts to cms monitoring repo and refactor git workflows

### PR DESCRIPTION
**Pull request by mrceyhun**
Mainly, moved sqoop scripts to this repo and arranged gh workflows.

- Move sqoop scripts to CMSMonitoring/sqoop repo from `CMSKubernetes/docker/sqoop`
- Adjust `sqoop/crontab.txt` for directory changes
- Create `build-sqoop.yml` to build and push sqoop docker image
- Rename `build.yml` with `build-go-tools.yml`
    - Refactor builds of `cmsmonit-alerts` and `cmsmonit-int` to push cern registry
    - Rename docker image of `cmsmonit-intelligence` to `cmsmonit-int`
    - `sqoop` image build will be triggered on tag **`sqoop-*.*.*`**
    - Go executables releases (`cmsmon-tools`) and docker image builds of `cmsmonit-alerts` and `cmsmonit-int` will be triggered on tag **`go-*.*.*`**
    - Test workflow improved changed to `syntaxcheck.yml`
    - New gh workflow definitions explained in README.md

If you've other suggestions for tag conventions, I can modify. For now, my suggestion is to use `sqoop-*` for sqoop, `go-` for golang related images. My tests were successful on all tags.

Fyi @vkuznet

### CODE REVIEW

**Comment by leggerf** [comment]
merging this, but pls also update cmsmonit-docs to reflect the changes

**Comment by mrceyhun** [comment]
I forget to mention that we need to create `CERN_LOGIN` and `CERN_TOKEN` secrets to login https://registry.cern.ch/ in GH workflows. I don't have right to create secrets in this repo. I can provide our CMS Monitoring user name and its token in secure way. Probably we need to ask Kevin, right?

**Comment by vkuznet** [comment]
@mrceyhun, yes in order to push stuff to CERN registry from GitHub Action we should add CERN_LOGIN and CERN_TOKEN into this repo. Since repo is under dmwm umbrella, the admin rights are in hands of @klannon  and @dciangot . First, they need to check if these secrets exists (I don't remember), and if they are not there we should provide proper credentials.

@klannon  and @dciangot, could you please check if CERN_LOGIN and CERN_SECRETS exists under Settings/Secrets area of this repo?

**Comment by dciangot** [comment]
@vkuznet yes CERN_LOGIN and CERN_TOKEN exist under Secrets/actions

**Comment by vkuznet** [comment]
@mrceyhun , then I suggest just to trigger the CI/CD build via GitHub Action. Create a new tag(s) and tests that all images will be created and uploaded properly.

**Comment by mrceyhun** [comment]
@vkuznet @klannon 
I created a new tag and GH wf build was exited with this [error](https://github.com/dmwm/CMSMonitoring/runs/5132259779?check_suite_focus=true#step:11:80):
```
unauthorized: unauthorized to access repository: cmsmonitoring/cmsmon-int, 
action: push: unauthorized to access repository: cmsmonitoring/cmsmon-int, 
action: push Error: exit status 1
```
Is it possible that current CERN_LOGIN does not have access to push image to  registry.cern.ch/cmsmonitoring ?

**Comment by vkuznet** [comment]
@mrceyhun , may be this is because originally we pushed images under cmsweb and for that credentials may be different than in cmsmonitoring area of registry. Please obtain proper credentials from @muhammadimranfarooqi and pass them securely to @klannon and/or @dciangot and ask them to recreate CERN_LOGIN and CERN_TOKEN secrets.

**Comment by mrceyhun** [comment]
Kevin changed the secrets with robot user of registry.cern.ch/cmsmonitoring. I tested them with new tags all builds are successful. These are the docker images builds and package release with git tags:
```
- registry.cern.ch/cmsmonitoring/sqoop:sqoop-0.0.1
- registry.cern.ch/cmsmonitoring/cmsmon-alerts:go-0.5.37
- registry.cern.ch/cmsmonitoring/cmsmon-int:go-0.5.37
- Release go-0.5.37
```

**Pull request merged**
